//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModels.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int Id { get; set; }
        public int RegId { get; set; }
        public string loantype { get; set; }
        public int loanamt { get; set; }
        public System.DateTime loanapplydate { get; set; }
        public System.DateTime loanissuedate { get; set; }
        public int roi { get; set; }
        public int coursefees { get; set; }
        public string course { get; set; }
        public string fathername { get; set; }
        public Nullable<int> fatherexp { get; set; }
        public Nullable<int> fexpcurrentcmpny { get; set; }
        public Nullable<int> rationcardno { get; set; }
        public Nullable<int> annualincome { get; set; }
        public string companyname { get; set; }
        public string designation { get; set; }
        public Nullable<int> totalexp { get; set; }
        public Nullable<int> expwithcurcmpny { get; set; }
    }
}
