//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModels.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string GaurdianType { get; set; }
        public string GaurdianName { get; set; }
        public string Address { get; set; }
        public string Citizenship { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public string EmailAddress { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime RegDate { get; set; }
        public string AccountType { get; set; }
        public string CitizenStatus { get; set; }
        public string InitialDepAmt { get; set; }
        public string IDProofType { get; set; }
        public string IDDocNo { get; set; }
        public string RefAccholderName { get; set; }
        public string RefAccholderNo { get; set; }
        public string RefAccholderAddress { get; set; }
    }
}
